services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: desiipr04/hoteles-enanos-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mailhog
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/hotel_db?allowPublicKeyRetrieval=true&useSSL=false"
      SPRING_DATASOURCE_USERNAME: desir
      SPRING_DATASOURCE_PASSWORD: 2004
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      APP_MAIL_ENABLED: "true"
      APP_MAIL_FROM: "hotelesenanos@gmail.com"
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_USERNAME: hotelesenanos@gmail.com
      SPRING_MAIL_PASSWORD: "jcbe gfyy wzuq qlcc"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
  frontend:
    build:
      context: ./Frontend
      dockerfile: Diseno/Dockerfile
    image: desiipr04/hoteles-enanos-frontend:latest
    ports:
      - "4173:80"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 2004
      MYSQL_DATABASE: hotel_db
      MYSQL_USER: desir
      MYSQL_PASSWORD: 2004
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql:ro
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  db_data:
