spring.application.name=hoteles-enanos-applications

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hotel_db?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#Depuracion
spring.jpa.properties.hibernate.format_sql=true

# Inicializacion de datos
spring.sql.init.mode=embedded
spring.jpa.defer-datasource-initialization=true

#Notificaciones por correo 
app.mail.enabled=${APP_MAIL_ENABLED:true}
app.mail.from=${APP_MAIL_FROM:reservas@hotelesenanos.com}

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:hotelesenanos@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:jcbe gfyy wzuq qlcc}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_SMTP_STARTTLS:true}
