spring.application.name=hoteles-enanos-applications

# MariaDB
spring.datasource.url=jdbc:mariadb://db:3306/hotelesenanos
spring.datasource.username=desir
spring.datasource.password=2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

#Depuracion
spring.jpa.properties.hibernate.format_sql=true

